[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
    [entryPoints.web.http.redirections]
      [entryPoints.web.http.redirections.entryPoint]
        to = "websecure"
        scheme = "https"
  [entryPoints.websecure]
    address = ":443"
  [entrypoints.metrics]
    address = ":8082"

[api]
  insecure = true
  dashboard = true

[metrics]
  prometheus = true

[providers.etcd]
  endpoints = ["etcd:2379"]
  rootKey = "master/traefik"

[certificatesResolvers.httpresolver.acme]
  email = "webmaster@local"
  storage = "acme-http.json"
  [certificatesResolvers.httpresolver.acme.httpChallenge]
    entryPoint = "web"

# Enable compression
[http.middlewares]
  [http.middlewares.content_compress.compress]
    defaultEncoding = "gzip"